version: "3.9"
services:
  nextjs:
    container_name: "hotelsSite"
    build:
      dockerfile: "./Dockerfile"
    volumes:
      - "./:/usr/src/app"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  db:
    container_name: "db-1"
    image: postgres:14.2
    volumes:
      - ./.pg-data:/var/lib/postgresql/data
      - ./data/db/initdb:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5432:5432"
    hostname: 127.0.0.1
